### ISSUE TITLE
Ads still exist

### ISSUE THREAD

**Issue by hddenkller** [ArizakiDev/SoundCloud-cracked#2]
Did not remove ads whatsoever
![image_2024-06-14_202019898](https://github.com/ArizakiDev/SoundCloud-cracked/assets/84136703/1e10d425-1b8e-4bf3-8668-355813eb2d19)

**Comment by ArizakiDev** [comment]
hi ! thanks for letting me know, Soundcloud has updated their verification system again, I'm taking care of it and I'm releasing an update in about thirty minutes with the return of the rpc discord.
